# Generated by Django 3.2.9 on 2021-11-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=124)),
                ('fees', models.DecimalField(decimal_places=4, max_digits=19)),
                ('minimum_balance', models.DecimalField(decimal_places=4, max_digits=19)),
                ('automated', models.BooleanField(default=False, verbose_name='Automated or Self-Directed')),
                ('advisor', models.BooleanField(default=False, verbose_name='Human Advisor Available')),
                ('ease_of_use', models.IntegerField(choices=[(1, 'Hardest'), (2, 'Hard'), (3, 'Average'), (4, 'Easy'), (5, 'Easiest')], default=3)),
            ],
        ),
    ]
